openapi: 3.0.0
info:
  title: Trending OSS API
  description: Trending OSS API
  version: 0.0.1
servers:
  - url: http://localhost:3000
paths:
  /:
    post:
      summary: Returns a list of repositories
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pastDays:
                  type: number
                  example: 1
                  default: 7
                  minimum: 1
                  maximum: 7
      responses:
        '200':
          description: A JSON array of repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
components:
  schemas:
    Repository:
      type: object
      properties:
        name:
          type: string
          example: 'vinay2897/trending-oss'
        stars:
          type: number
          example: 0
